runtime: nodejs18

service: default
env: standard

env_variables:
  DEEPSEEK_API_ENDPOINT: "https://api.deepseek.com/v1"
  NODE_ENV: "production"
  API_BASE_URL: "https://primordial-hall-448409-j6.nn.r.appspot.com"

handlers:
  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$
    secure: always

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
